
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka
  instance:
    instance-id: shop-gateway9002
    prefer-ip-address: true
spring:
  application:
    name: shop-gateway
  zipkin:
    base-url: http://localhost:9003
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    user-consumer: /user/**
  TwoFilter:
    pre:
      disable: true
logging:
    level: info